name: Validate PR before adding to merge queue

on:
  pull_request:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Run fast CI (emulated by a short sleep)
      run: ./pr-check.sh
