name: Validate PR

on:
  pull_request:
  merge_queue:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Display info
      run: | 
        pwd
        tree -a -I '.git'
        git status
    - name: Validate files
      run: ./pr-check.sh
